name: Test and Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [18.x]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Linux Dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb libxkbfile-dev pkg-config libsecret-1-dev libxss1 dbus xauth libgbm-dev libgtk-3-0 libasound2

    - name: Install Dependencies
      run: npm ci

    - name: Build Extension
      run: npm run compile

    - name: Run Tests (Linux)
      if: runner.os == 'Linux'
      run: |
        export DISPLAY=':99.0'
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        sleep 3
        npm test

    - name: Run Tests (Windows)
      if: runner.os == 'Windows'
      run: npm test
      env:
        CODE_EXECUTABLE: 'C:\Program Files\Microsoft VS Code\Code.exe'

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-${{ matrix.os }}
        path: test-results/
        retention-days: 30

  publish:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Package Extension
        run: |
          npm install -g @vscode/vsce
          vsce package

      - name: Upload VSIX
        uses: actions/upload-artifact@v4
        with:
          name: extension
          path: "*.vsix"

  publish-marketplace:
    needs: publish
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Download VSIX
        uses: actions/download-artifact@v4
        with:
          name: extension

      - name: Install VSCE
        run: npm install -g @vscode/vsce

      - name: Publish to Marketplace
        run: vsce publish -p ${{ secrets.VSCE_PAT }}
        continue-on-error: true 